id: https://example.com/DH_LinkML
name: DH_LinkML
description: The DataHarmonizer template for editing a schema.
version: 1.0.0
in_language:
- en
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  ONTOLOGY1: http://purl.obolibrary.org/obo/ONTOLOGY1_
classes:
  dh_interface:
    name: dh_interface
    description: A DataHarmonizer interface
    from_schema: https://example.com/GRDI
  Schema:
    name: Schema
    description: The top-level description of a LinkML schema.  A schema contains
      classes for describing one or more DataHarmonizer templates, fields/columns,
      and picklists (which are themselves LinkML classes, slots, and enumerations)
    see_also: templates/schema_editor/SOP.pdf
    is_a: dh_interface
    slots:
    - name
    - description
    - id
    - version
    - in_language
    - default_prefix
    slot_usage:
      name:
        rank: 1
        slot_group: key
        pattern: ^([A-Z][a-z0-9]+)+$
        description: The coding name of a LinkML schema.
        comments: 'This is a **CamelCase** formatted name in the LinkML standard naming
          convention.


          A schema contains classes for describing one or more DataHarmonizer templates,
          fields/columns, and picklists (which are themselves LinkML classes, slots,
          and enumerations).'
        examples:
        - value: Wastewater
        range: string
      description:
        rank: 2
        slot_group: attributes
        description: A plan text description of this LinkML schema.
        range: string
      id:
        rank: 3
        slot_group: attributes
      version:
        rank: 4
        slot_group: attributes
        required: true
        description: A semantic version identifier for this schema.
        comments: See https://semver.org/
      in_language:
        rank: 5
        slot_group: attributes
      default_prefix:
        rank: 6
        slot_group: attributes
  Slot:
    name: Slot
    description: One or more slots contained in given schema. A slot can be used in
      one or more classes (templates).  A slot defines a visible column in a template,
      and can be a basic number, date, string, picklist (categorical or ordinal),
      or other single-field datatype.
    slots:
    - schema_id
    - name
    - title
    - description
    - slot_uri
    - range
    - identifier
    - multivalued
    - required
    - recommended
    - minimum_value
    - maximum_value
    - pattern
    - comments
    - examples
    slot_usage:
      schema_id:
        rank: 1
        slot_group: key
        description: The coding name of the schema this slot is contained in.
        comments: This is a snake_case formatted name in the LinkML standard naming
          convention.
      name:
        rank: 2
        slot_group: key
        description: The coding name of this LinkML schema slot.
        comments: A slot can be used in one or more classes (templates). A slot appears
          as a visible column in a spreadsheet (template) tab, and can define a basic
          number, date, string, picklist (categorical or ordinal), or other single-field
          datatype.
        range: string
      title:
        rank: 3
        slot_group: attributes
        range: string
        description: The plain language name of this LinkML schema slot.
        comments: This can be displayed in applications and documentation.
      description:
        rank: 4
        slot_group: attributes
        description: A plan text description of this LinkML schema slot.
        range: string
      slot_uri:
        rank: 5
        slot_group: attributes
      range:
        rank: 6
        slot_group: attributes
      identifier:
        rank: 7
        slot_group: attributes
        description: A boolean TRUE indicates this slot is an identifier, or refers
          to one.
      multivalued:
        rank: 8
        slot_group: attributes
        description: A boolean TRUE indicates this slot can hold more than one values
          taken from its range.
      required:
        rank: 9
        slot_group: attributes
        description: A boolean TRUE indicates this slot is a mandatory data field.
        comments: A mandatory data field will fail validation if empty.
      recommended:
        rank: 10
        slot_group: attributes
        description: A boolean TRUE indicates this slot is a recommended data field.
      minimum_value:
        rank: 11
        slot_group: attributes
      maximum_value:
        rank: 12
        slot_group: attributes
      pattern:
        rank: 13
        slot_group: attributes
      comments:
        rank: 14
        slot_group: attributes
      examples:
        rank: 15
        slot_group: attributes
  Enum:
    name: Enum
    description: One or more enumerations in given schema.  An enumeration can be
      used in the "range" or "any of" attribute of a slot.  Each enumeration has a
      flat list or hierarchy of permitted values.
    slots:
    - schema_id
    - name
    - title
    - description
    - enum_uri
    - permissible_values
    slot_usage:
      schema_id:
        rank: 1
        slot_group: key
        description: The coding name of the schema this enumeration is contained in.
      name:
        rank: 2
        slot_group: key
        range: WhitespaceMinimizedString
        description: The plain language name of this LinkML schema enumeration.
        comments: See https://linkml.io/linkml/schemas/enums.html
      title:
        rank: 3
        slot_group: attributes
        range: WhitespaceMinimizedString
        description: The plain language name of this enumeration menu.
      description:
        rank: 4
        slot_group: attributes
        range: WhitespaceMinimizedString
        description: A plan text description of this LinkML schema enumeration menu
          of terms.
      enum_uri:
        rank: 5
        slot_group: attributes
      permissible_values:
        rank: 6
        slot_group: attributes
  Class:
    name: Class
    description: One or more classes contained in given schema.  Each class can be
      displayed in DataHarmonizer in a spreadsheet tab.  A class may be a top-level
      DataHarmonizer "template", or it may be a subordinate 1-many class linked to
      a parent class by a primary key field.
    slots:
    - schema_id
    - name
    - title
    - description
    - version
    - class_uri
    - slot_usage
    - container_root
    - alias
    - owner
    - Inlined as list
    slot_usage:
      schema_id:
        rank: 1
        slot_group: key
        description: The coding name of the schema this class is contained in.
      name:
        rank: 2
        slot_group: key
        range: string
        pattern: ^([A-Z][a-z0-9]+)+$
        description: A class contained in given schema.
        comments: Each class can be displayed in DataHarmonizer in a spreadsheet tab.
          A class may be visible as a top-level DataHarmonizer "template", or it may
          be a subordinate 1-many class linked to a parent class by a primary key
          field.
        examples:
        - value: WastewaterAMR|WastewaterPathogenAgnostic
      title:
        rank: 3
        slot_group: attributes
        range: string
        description: The plain language name of a LinkML schema class.
      description:
        rank: 4
        slot_group: attributes
        range: string
      version:
        rank: 5
        slot_group: attributes
        description: A semantic version identifier.  See https://semver.org/
      class_uri:
        rank: 6
        slot_group: attributes
      slot_usage:
        rank: 7
        slot_group: attributes
      container_root:
        rank: 8
        slot_group: attributes
      alias:
        rank: 9
        slot_group: attributes
      owner:
        rank: 10
        slot_group: attributes
      Inlined as list:
        rank: 11
        slot_group: attributes
  SlotUsage:
    name: SlotUsage
    description: A table linking slots to classes they appear in, as well as attributes
      which override the generic slot inheritance.
    slots:
    - schema_id
    - class
    - slot
    - slot_group
    - rank
    - inlined
    - identifier
    - multivalued
    - required
    - recommended
    slot_usage:
      schema_id:
        rank: 1
        slot_group: key
      class:
        rank: 2
        slot_group: key
      slot:
        rank: 3
        slot_group: attributes
      slot_group:
        rank: 4
        slot_group: attributes
      rank:
        rank: 5
        slot_group: attributes
      inlined:
        rank: 6
        slot_group: attributes
      identifier:
        rank: 7
        slot_group: attributes
      multivalued:
        rank: 8
        slot_group: attributes
      required:
        rank: 9
        slot_group: attributes
      recommended:
        rank: 10
        slot_group: attributes
  Prefix:
    name: Prefix
    description: A prefix used in the URIs mentioned in this schema.
    slots:
    - schema_id
    - prefix
    - reference
    slot_usage:
      schema_id:
        rank: 1
        slot_group: key
        description: The coding name of the schema this prefix is listed in.
      prefix:
        rank: 2
        slot_group: key
      reference:
        rank: 3
        slot_group: attributes
  Container:
    tree_root: true
    attributes:
      Schemas:
        range: Schema
        multivalued: true
        inlined_as_list: true
      Classes:
        range: Class
        multivalued: true
        inlined_as_list: true
      Slots:
        range: Slot
        multivalued: true
        inlined_as_list: true
      SlotUsages:
        range: SlotUsage
        multivalued: true
        inlined_as_list: true
      Enums:
        range: Enum
        multivalued: true
        inlined_as_list: true
      Prefixes:
        range: Prefix
        multivalued: true
        inlined_as_list: true
slots:
  name:
    name: name
    title: Name
    identifier: true
    required: true
  description:
    name: description
    title: Description
    required: true
  id:
    name: id
    title: ID
    description: A unique URI for identifying this LinkML schema.
    identifier: true
    range: uri
    required: true
  version:
    name: version
    title: Version
    identifier: true
    range: string
    pattern: ^\d+\.\d+\.\d+$
  in_language:
    name: in_language
    title: Languages
    description: A list of i18n language codes that this schema is available in
    comments: The first listed schema is the default (usually english), while remaining
      ones are language overlays compiled into a locales/ subfolder.
    range: LanguagesMenu
    multivalued: true
  default_prefix:
    name: default_prefix
    title: Default prefix
    comments: A prefix to assume all classes and slots can be addressed by.
    range: uri
    required: true
  schema_id:
    name: schema_id
    title: Schema
    identifier: true
    range: schema
    required: true
  title:
    name: title
    title: Title
    required: true
  slot_uri:
    name: slot_uri
    title: Slot URI
    description: A URI for identifying this slot's semantic type.
    range: uri
  range:
    name: range
    title: Range
    description: The range or ranges a slot is associated with.  If more than one,
      this appears in the slot's specification as a list of "any of" ranges.
    range: DataTypeMenu
    multivalued: true
  identifier:
    name: identifier
    title: Identifier
    range: TrueFalseMenu
  multivalued:
    name: multivalued
    title: Multivalued
    range: TrueFalseMenu
  required:
    name: required
    title: Required
    range: TrueFalseMenu
  recommended:
    name: recommended
    title: Recommended
    range: TrueFalseMenu
  minimum_value:
    name: minimum_value
    title: Minimum_value
    description: A minimum value which is appropriate for the range data type of the
      slot.
    range: integer
  maximum_value:
    name: maximum_value
    title: Maximum_value
    description: A maximum value which is appropriate for the range data type of the
      slot.
    range: integer
  pattern:
    name: pattern
    title: Pattern
    description: A regular expression pattern used to validate a slot's string range
      data type content.
    comments: Regular expressions can begin with ^ to ensure start of string is tested,
      and $ to ensure up to end is tested.
    range: WhitespaceMinimizedString
  comments:
    name: comments
    title: Comments
    description: A free text field for adding other comments to guide usage of field.
    range: WhitespaceMinimizedString
  examples:
    name: examples
    title: Examples
    description: A free text field for including examples of string, numeric, date
      or categorical values.
    range: WhitespaceMinimizedString
  enum_uri:
    name: enum_uri
    title: Enum URI
    description: A URI for identifying this enumeration's semantic type.
    range: uri
  permissible_values:
    name: permissible_values
    title: Permissible values
    range: string
  class_uri:
    name: class_uri
    title: Class URI
    range: uri
  slot_usage:
    name: slot_usage
    title: Slot Usage
    range: string
  container_root:
    name: container_root
    title: Container
    range: TrueFalseMenu
  alias:
    name: alias
    title: Alias
    range: string
  owner:
    name: owner
    title: Owner
    range: string
  Inlined as list:
    name: Inlined as list
    title: Inlined as list
    range: TrueFalseMenu
  class:
    name: class
    title: Class
    identifier: true
    range: WhitespaceMinimizedString
    required: true
  slot:
    name: slot
    title: Slot
    identifier: true
    range: WhitespaceMinimizedString
    required: true
  slot_group:
    name: slot_group
    title: Slot Group
    range: WhitespaceMinimizedString
  rank:
    name: rank
    title: Rank
    range: integer
  inlined:
    name: inlined
    title: Inlined
    range: TrueFalseMenu
  prefix:
    name: prefix
    title: Prefix
    description: The namespace prefix string.
    identifier: true
    range: string
    required: true
  reference:
    name: reference
    title: Reference
    description: The URI the prefix expands to.
    range: uri
enums:
  TrueFalseMenu:
    name: TrueFalseMenu
    permissible_values:
      'TRUE':
        text: 'TRUE'
      'FALSE':
        text: 'FALSE'
  DataTypeMenu:
    name: DataTypeMenu
    permissible_values:
      string:
        text: string
      WhitespaceMinimizedString:
        text: WhitespaceMinimizedString
      boolean:
        text: boolean
      integer:
        text: integer
      decimal:
        text: decimal
      double:
        text: double
      float:
        text: float
      date:
        text: date
      datetime:
        text: datetime
      date_or_datetime:
        text: date_or_datetime
      time:
        text: time
      uriorcurie:
        text: uriorcurie
      curie:
        text: curie
      uri:
        text: uri
      schema:
        text: schema
      Provenance:
        text: Provenance
      TrueFalseMenu:
        text: TrueFalseMenu
      DataTypeMenu:
        text: DataTypeMenu
      LanguagesMenu:
        text: LanguagesMenu
  LanguagesMenu:
    name: LanguagesMenu
    permissible_values:
      en:
        text: en
      fr:
        text: fr
types:
  WhitespaceMinimizedString:
    name: WhitespaceMinimizedString
    typeof: string
    description: 'A string that has all whitespace trimmed off of beginning and end,
      and all internal whitespace segments reduced to single spaces. Whitespace includes
      #x9 (tab), #xA (linefeed), and #xD (carriage return).'
    base: str
    uri: xsd:token
  Provenance:
    name: Provenance
    typeof: string
    description: A field containing a DataHarmonizer versioning marker. It is issued
      by DataHarmonizer when validation is applied to a given row of data.
    base: str
    uri: xsd:token
settings:
  Title_Case: (((?<=\b)[^a-z\W]\w*?|[\W])+)
  UPPER_CASE: '[A-Z\W\d_]*'
  lower_case: '[a-z\W\d_]*'
