name: Build and test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build:lib
      - run: yarn test
